version: "3.7"
services:
  postgres-tts:
    container_name: postgres-tts
    image: postgres-tts
  tts-app:
    container_name: tts-app
    external_links:
      - postgres-tts
    depends_on:
      - postgres-tts