version: "3.7"
services:
  postgres-tts:
    container_name: postgres-tts
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/data/db
    ports:
      - 5433:5433
  tts-app:
    container_name: tts-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    external_links:
      - postgres-tts
    depends_on:
      - postgres-tts
volumes:
  pgdata:
      external: false