version: "3.7"
services:
  postgres-tts:
    container_name: postgres-tts
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - pgdata:/data/db
    ports:
      - 5433:5433
  tts-app:
    container_name: tts-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    external_links:
      - postgres-tts
    depends_on:
      - postgres-tts
volumes:
  pgdata:
      external: false