version: "3.7"
services:
  postgres-tts:
    container_name: postgres-tts
    image: postgres
    restart: always
    env_file: .env.prod
    volumes:
      - pgdata:/data/db
    ports:
      - 5433:5433
  tts-app:
    container_name: tts-app
    restart: always
    build: .
    env_file: .env.prod
    ports:
      - ${PORT}:80
    external_links:
      - postgres-tts
    depends_on:
      - postgres-tts
volumes:
  pgdata: