FROM nikolaik/python-nodejs:python3.9-nodejs16-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

RUN pip3 install --upgrade pip setuptools wheel

RUN curl -LJO https://github.com/coqui-ai/TTS/archive/refs/tags/v0.6.1.tar.gz

RUN tar xvf TTS-0.6.1.tar.gz

RUN mv TTS-0.6.1 TTS

WORKDIR /app/TTS

RUN pip3 install .

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

CMD [ "npm", "run", "dev" ]