version: "3.7"
services:
  postgres-tts:
    container_name: postgres-tts
    image: postgres-tts
  tts-app:
    container_name: tts-app
    environment:
      - STATIC_PATH=/app/static
      - AUDIO_PATH=/app/audio
      - MODEL_PATH=/app/tts-config
      - SECRET_KEY_PATH=/app/sslcert/server.key
      - CERTIFICATE_PATH=/app/sslcert/server.crt
    external_links:
      - postgres-tts
    depends_on:
      - postgres-tts