version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env.prod
    volumes:
      - pgdata:/data/db
    ports:
      - 5432:5432
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env.prod
    ports:
      - ${PORT}:80
    external_links:
      - postgres
    depends_on:
      - postgres
volumes:
  pgdata: