name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Removing old server deployment to another folder by executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: rm -r /home/${{ secrets.USERNAME }}/bel-tts-server/*

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/${{ secrets.USERNAME }}/bel-tts-server"
        
    - name: Building docker container by executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: docker-compose -f /home/${{ secrets.USERNAME }}/bel-tts-server/docker-compose.yml -f /home/${{ secrets.USERNAME }}/bel-tts-server/docker-compose.prod.yml build  
        
      
    - name: Executing docker container by executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: docker-compose -f /home/${{ secrets.USERNAME }}/bel-tts-server/docker-compose.yml -f /home/${{ secrets.USERNAME }}/bel-tts-server/docker-compose.prod.yml up -d
